#!/usr/bin/env node
/**
 * §6.6 QC gate runner — checks every shipped model, prints what it cannot check.
 *
 *   node scripts/tripo_qc.mjs                 report + fail on any ENFORCED failure
 *   node scripts/tripo_qc.mjs --warn-only     report only (exit 0)
 *   node scripts/tripo_qc.mjs --dir public/models
 *
 * Runs against public/models, which is Drive-only, so this belongs to the asset-runner
 * CI job and not the fast tier. It exits 0 with a clear message when the assets are
 * absent rather than pretending to have passed.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { qcAsset, NOT_ENFORCED } from './tripo/qc.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const arg = (f, d) => { const i = process.argv.indexOf(f); return i >= 0 ? process.argv[i + 1] : d; };
const DIR = path.join(ROOT, arg('--dir', 'public/models'));
const WARN_ONLY = process.argv.includes('--warn-only');

if (!fs.existsSync(DIR)) {
  console.log(`§6.6 QC gate: ${path.relative(ROOT, DIR)} is not in this checkout (Drive-only).`);
  console.log('Nothing checked. This is not a pass — run it where the assets are.');
  process.exit(0);
}

const files = fs.readdirSync(DIR).filter((f) => f.endsWith('.glb')).sort();
const results = files.map((f) => qcAsset(path.join(DIR, f)));

/**
 * Baseline.
 *
 * 111 of 153 shipped models are over their §6.8 budget, because the generator used one
 * face_limit for every class: every asset is ~112,800 triangles whether it is a hero
 * mech or a supply crate. Frames fit inside their 180k budget by luck; props are 9.4x
 * over a 12k budget, and 32 props at 113k is 3.6M triangles of dressing against §6.8's
 * 600k per-level ceiling.
 *
 * That is a real backlog, not a reason to disable the gate — and a gate that fails 111
 * files on its first run gets switched off by the second person who sees it. So the
 * current state is recorded as a baseline and the gate fails on REGRESSION: a model that
 * was passing and now fails, or a known-bad model that got worse. The backlog shrinks by
 * re-baselining after each fix, never by raising a budget.
 */
const BASELINE_PATH = path.join(ROOT, 'content', 'asset-qc-baseline.json');
const baseline = fs.existsSync(BASELINE_PATH)
  ? JSON.parse(fs.readFileSync(BASELINE_PATH, 'utf8'))
  : null;

if (process.argv.includes('--write-baseline')) {
  const known = {};
  for (const r of results) if (r.fail.length) known[r.file] = { tris: r.tris, fails: r.fail.length };
  fs.writeFileSync(BASELINE_PATH, `${JSON.stringify({
    $comment: 'GENERATED by scripts/tripo_qc.mjs --write-baseline. Known §6.8 budget debt. '
      + 'Shrink it by fixing assets and re-baselining; never by raising a budget.',
    known,
  }, null, 2)}\n`);
  console.log(`wrote baseline: ${Object.keys(known).length} known-failing models`);
  process.exit(0);
}

const regressions = [];
if (baseline) {
  for (const r of results) {
    const was = baseline.known[r.file];
    if (r.fail.length && !was) regressions.push(`${r.file}: NEW failure (${r.fail[0]})`);
    else if (r.fail.length && was && r.tris > was.tris) {
      regressions.push(`${r.file}: got worse — ${was.tris} → ${r.tris} tris`);
    }
  }
}

const failed = results.filter((r) => r.fail.length);
const warned = results.filter((r) => r.warn.length);

// Only regressions are printed per-file. The known backlog is a count, because 111
// identical "over budget" lines every run is what teaches people to skip the output.
for (const r of regressions) console.error(`REGRESSION ${r}`);
if (!baseline) {
  for (const r of failed) {
    console.error(`FAIL ${r.file}  [${r.cls} lod${r.lod}, ${r.tris} tris]`);
    for (const f of r.fail) console.error(`       ${f}`);
  }
}

// Warnings are grouped by kind, not per file: 153 copies of the same PNG message is
// noise that buries the one line that matters.
const warnKinds = new Map();
for (const r of warned) {
  for (const w of r.warn) {
    const kind = w.replace(/"[^"]*"/g, '"…"').replace(/[\d.]+/g, 'N');
    if (!warnKinds.has(kind)) warnKinds.set(kind, []);
    warnKinds.get(kind).push(r.file);
  }
}
if (warnKinds.size) {
  console.log('\nwarnings (grouped):');
  for (const [kind, files] of warnKinds) {
    console.log(`  ${files.length.toString().padStart(4)} x ${kind}`);
    console.log(`         e.g. ${files.slice(0, 3).join(', ')}${files.length > 3 ? ' …' : ''}`);
  }
}

console.log('\nnot enforced by this gate — stated so nobody reads a pass as full coverage:');
for (const d of NOT_ENFORCED.DEFERRED) console.log(`  DEFERRED  ${d}`);
for (const m of NOT_ENFORCED.MANUAL) console.log(`  MANUAL    ${m}`);

const byClass = results.reduce((a, r) => { a[r.cls] = (a[r.cls] ?? 0) + 1; return a; }, {});
console.log(
  `\n§6.6 QC gate: ${results.length} models `
  + `(${Object.entries(byClass).map(([k, v]) => `${v} ${k}`).join(', ')}) — `
  + `${failed.length} over budget, ${warned.length} with warnings`
  + (baseline ? `, ${Object.keys(baseline.known).length} known (baselined)` : ''),
);
if (regressions.length) console.error(`\n${regressions.length} REGRESSION(S) — see above`);
else if (baseline) console.log('no regressions against the baseline');

process.exit(regressions.length && !WARN_ONLY ? 1 : 0);
