// GENERATED by scripts/content_schema.mjs --types. Do not edit.

export interface Frame {
  id: string;
  name: string;
  class: string;
  tons: number;
  speedKmh: number;
  twistArcDeg: number;
  jumpJets: boolean;
  heatSinks: number;
  hardpoints: unknown[];
  defaultLoadout: unknown[];
  role?: string;
}

export interface Weapon {
  id: string;
  name: string;
  type: string;
  damage: number;
  salvo?: number;
  heat: number;
  cooldown: number;
  range: number;
  projectileSpeed?: number;
  spread?: number;
  ammo?: number;
  tons?: number;
  tags?: unknown[];
}

export interface Mission {
  id: string;
  stage: number;
  title: string;
  map: string;
  spawn: Record<string, unknown>;
  playerMech: string;
  steps: unknown[];
  extract?: unknown[];
  designFile?: string;
  branch?: string;
  allies?: unknown[];
  structures?: unknown[];
  artillery?: Record<string, unknown>;
  timedVO?: unknown[];
  heatMult?: number;
  playerWoundVO?: unknown[];
}

